name: Feature Request
description: Suggest an idea for this project
title: "Feature Request Title Here"
labels: ["Enhancement", "Feature", "Request"]

body:
  - type: markdown
    attributes:
      value: "## Problem Related to the Feature Request"
  - type: textarea
    id: problem-description
    attributes:
      label: "Problem Description"
      description: "Describe the problem that this feature request aims to solve"
      placeholder: "Ex. I'm always frustrated when..."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Desired Solution"
  - type: textarea
    id: desired-solution
    attributes:
      label: "Solution Description"
      description: "A clear and concise description of what you want to happen"
      placeholder: "Describe the feature you would like to see implemented"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Alternatives Considered"
  - type: textarea
    id: alternative-solutions
    attributes:
      label: "Alternative Solutions"
      description: "Describe any alternative solutions or features you've considered"
      placeholder: "Detail any alternative solutions you have thought about"

  - type: markdown
    attributes:
      value: "#### Additional Context"
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context (optional)"
      description: "Provide any additional context or screenshots about the feature request"
      placeholder: "Include any supplementary information or images that might help illustrate your feature request"
