version: '3'

services:
  db:
    image: postgres:alpine
    container_name: the-agent-database
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432

  api:
    image: appifyhub/the-agent:latest
    container_name: the-agent-api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "80:80"

volumes:
  postgres:
    driver: local
