"""Message Attachments

Revision ID: 01b6bbaa0e0f
Revises: cb35264b5443
Create Date: 2024-06-07 20:14:40.043941

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01b6bbaa0e0f'
down_revision: Union[str, None] = 'cb35264b5443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'chat_message_attachments',
        sa.Column('id', sa.String(), nullable = False),
        sa.Column('chat_id', sa.String(), nullable = False),
        sa.Column('message_id', sa.String(), nullable = False),
        sa.Column('size', sa.Integer(), nullable = True),
        sa.Column('last_url', sa.String(), nullable = True),
        sa.Column('last_url_until', sa.Integer(), nullable = True),
        sa.Column('extension', sa.String(), nullable = True),
        sa.Column('mime_type', sa.String(), nullable = True),
        sa.ForeignKeyConstraint(['chat_id', 'message_id'], ['chat_messages.chat_id', 'chat_messages.message_id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message_attachments')
    # ### end Alembic commands ###
