"""google_ai_key

Revision ID: 0bbfd2411b29
Revises: 2768d487d75c
Create Date: 2025-07-26 23:02:23.767286

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bbfd2411b29"
down_revision: Union[str, None] = "2768d487d75c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulants", sa.Column("google_ai_key", sa.String(), nullable = True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulants", "google_ai_key")
    # ### end Alembic commands ###
