"""attachments_external_id_index

Revision ID: 2768d487d75c
Revises: ab5ca2f70080
Create Date: 2025-07-20 20:47:42.425576

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2768d487d75c"
down_revision: Union[str, None] = "ab5ca2f70080"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_ext_id", "chat_message_attachments", ["ext_id"], unique = False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ext_id", table_name = "chat_message_attachments")
    # ### end Alembic commands ###
