"""user_about_me

Revision ID: 2791b8eece2e
Revises: bd6531868af1
Create Date: 2025-12-18 22:15:16.988237

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import BYTEA

# revision identifiers, used by Alembic.
revision: str = "2791b8eece2e"
down_revision: Union[str, None] = "bd6531868af1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("simulants", sa.Column("about_me", BYTEA, nullable = True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulants", "about_me")
    # ### end Alembic commands ###
