"""tool_choices

Revision ID: 286e96152dc5
Revises: 5e420f984e8d
Create Date: 2025-07-05 22:52:09.145185

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "286e96152dc5"
down_revision: Union[str, None] = "5e420f984e8d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulants", sa.Column("tool_choice_chat", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_reasoning", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_copywriting", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_vision", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_hearing", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_images_gen", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_images_edit", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_images_restoration", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_images_inpainting", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_images_background_removal", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_search", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_embedding", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_api_fiat_exchange", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_api_crypto_exchange", sa.String(), nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_api_twitter", sa.String(), nullable = True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulants", "tool_choice_api_twitter")
    op.drop_column("simulants", "tool_choice_api_crypto_exchange")
    op.drop_column("simulants", "tool_choice_api_fiat_exchange")
    op.drop_column("simulants", "tool_choice_embedding")
    op.drop_column("simulants", "tool_choice_search")
    op.drop_column("simulants", "tool_choice_images_background_removal")
    op.drop_column("simulants", "tool_choice_images_inpainting")
    op.drop_column("simulants", "tool_choice_images_restoration")
    op.drop_column("simulants", "tool_choice_images_edit")
    op.drop_column("simulants", "tool_choice_images_gen")
    op.drop_column("simulants", "tool_choice_hearing")
    op.drop_column("simulants", "tool_choice_vision")
    op.drop_column("simulants", "tool_choice_copywriting")
    op.drop_column("simulants", "tool_choice_reasoning")
    op.drop_column("simulants", "tool_choice_chat")
    # ### end Alembic commands ###
