"""telegram-ids-bigint

Revision ID: 31bcb8d29bc1
Revises: 75bdefa1ee57
Create Date: 2024-08-29 20:50:23.550713

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31bcb8d29bc1'
down_revision: Union[str, None] = '75bdefa1ee57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'simulants', 'telegram_user_id',
        existing_type = sa.INTEGER(),
        type_ = sa.BigInteger(),
        existing_nullable = True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'simulants', 'telegram_user_id',
        existing_type = sa.BigInteger(),
        type_ = sa.INTEGER(),
        existing_nullable = True,
    )
    # ### end Alembic commands ###
