"""chat_types

Revision ID: 32e1f74679b4
Revises: 47a883fd74c4
Create Date: 2025-08-07 15:17:42.599898

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32e1f74679b4"
down_revision: Union[str, None] = "47a883fd74c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    chattype_enum = sa.Enum("standalone_web", "standalone_app", "extension_web", "telegram", "whatsapp", name = "chattype")
    chattype_enum.create(op.get_bind())

    op.add_column(
        "chat_configs",
        sa.Column(
            "chat_type",
            chattype_enum,
            nullable = False,
            server_default = "telegram",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_configs", "chat_type")
    sa.Enum(name = "chattype").drop(op.get_bind())
    # ### end Alembic commands ###
