"""remove_obsolete_image_tools

Revision ID: 338582422265
Revises: 57f8712f47c2
Create Date: 2026-01-24 13:38:36.164104

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "338582422265"
down_revision: Union[str, None] = "57f8712f47c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulants", "tool_choice_images_inpainting")
    op.drop_column("simulants", "tool_choice_images_background_removal")
    op.drop_column("simulants", "tool_choice_images_restoration")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # @formatter:off
    op.add_column("simulants", sa.Column("tool_choice_images_restoration", sa.VARCHAR(), autoincrement = False, nullable = True))
    op.add_column("simulants", sa.Column("tool_choice_images_background_removal", sa.VARCHAR(), autoincrement = False, nullable = True))  # noqa: E501
    op.add_column("simulants", sa.Column("tool_choice_images_inpainting", sa.VARCHAR(), autoincrement = False, nullable = True))
    # @formatter:on
    # ### end Alembic commands ###
