"""chat_reply_chance

Revision ID: 36c73da185ec
Revises: c4b16e92a201
Create Date: 2024-08-05 13:13:14.502569

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36c73da185ec"
down_revision: Union[str, None] = "c4b16e92a201"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_configs", sa.Column("reply_chance_percent", sa.Integer(), nullable = True))
    # noinspection SqlNoDataSourceInspection,SqlConstantExpression
    op.execute("UPDATE chat_configs SET reply_chance_percent = 100 WHERE reply_chance_percent IS NULL")
    op.alter_column("chat_configs", "reply_chance_percent", nullable = False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_configs", "reply_chance_percent")
    # ### end Alembic commands ###
