"""Nullable chat config

Revision ID: 3ba10b2b7ae5
Revises: a7aae15ea264
Create Date: 2024-06-10 21:48:14.084157

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ba10b2b7ae5'
down_revision: Union[str, None] = 'a7aae15ea264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'chat_configs', 'persona_code',
        existing_type = sa.VARCHAR(),
        nullable = True
    )
    op.alter_column(
        'chat_configs', 'persona_name',
        existing_type = sa.VARCHAR(),
        nullable = True
    )
    op.alter_column(
        'chat_configs', 'language_iso_code',
        existing_type = sa.VARCHAR(),
        nullable = True
    )
    op.alter_column(
        'chat_configs', 'language_name',
        existing_type = sa.VARCHAR(),
        nullable = True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'chat_configs', 'language_name',
        existing_type = sa.VARCHAR(),
        nullable = False
    )
    op.alter_column(
        'chat_configs', 'language_iso_code',
        existing_type = sa.VARCHAR(),
        nullable = False
    )
    op.alter_column(
        'chat_configs', 'persona_name',
        existing_type = sa.VARCHAR(),
        nullable = False
    )
    op.alter_column(
        'chat_configs', 'persona_code',
        existing_type = sa.VARCHAR(),
        nullable = False
    )
    # ### end Alembic commands ###
