"""tools_cache

Revision ID: 43a9b13811e6
Revises: a89b3d0f78d1
Create Date: 2024-08-10 01:23:34.772410

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43a9b13811e6"
down_revision: Union[str, None] = "a89b3d0f78d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tools_cache",
        sa.Column("key", sa.String(), nullable = False),
        sa.Column("value", sa.Text(), nullable = False),
        sa.Column("created_at", sa.DateTime(), nullable = False),
        sa.Column("expires_at", sa.DateTime(), nullable = True),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tools_cache")
    # ### end Alembic commands ###
