"""x_ai_support

Revision ID: 4f143993b73f
Revises: d6f7c1204b44
Create Date: 2026-03-19 00:34:14.499802

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import BYTEA

# revision identifiers, used by Alembic.
revision: str = "4f143993b73f"
down_revision: Union[str, None] = "d6f7c1204b44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulants", sa.Column("x_ai_key", BYTEA, nullable = True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulants", "x_ai_key")
    # ### end Alembic commands ###
