"""add_connect_key_to_users

Revision ID: 5472fe3215da
Revises: a0ecabe6256b
Create Date: 2025-11-02 19:31:36.868557

"""
import secrets
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

CONNECT_KEY_CHARS = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"


# revision identifiers, used by Alembic.
revision: str = "5472fe3215da"
down_revision: Union[str, None] = "a0ecabe6256b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add column as nullable first
    op.add_column("simulants", sa.Column("connect_key", sa.String(), nullable = True))

    # Step 2: Backfill existing users with unique connect keys
    bind = op.get_bind()
    session = Session(bind = bind)

    # Get all existing users
    users = session.execute(sa.text("SELECT id FROM simulants WHERE connect_key IS NULL")).fetchall()

    for user_row in users:
        user_id = user_row[0]
        # Generate unique connect key for each user
        connect_key = generate_unique_connect_key(session)
        session.execute(
            sa.text("UPDATE simulants SET connect_key = :key WHERE id = :id"),
            {"key": connect_key, "id": user_id},
        )

    session.commit()

    # Step 3: Make column non-nullable and add unique index
    op.alter_column("simulants", "connect_key", nullable = False)
    op.create_index(op.f("ix_simulants_connect_key"), "simulants", ["connect_key"], unique = True)


def generate_unique_connect_key(session: Session) -> str:
    max_attempts = 100
    for attempt in range(max_attempts):
        # Generate 12 random characters from allowed charset
        key_chars = [secrets.choice(CONNECT_KEY_CHARS) for _ in range(12)]
        formatted_key = f"{''.join(key_chars[0:4])}-{''.join(key_chars[4:8])}-{''.join(key_chars[8:12])}"

        # Check uniqueness
        result = session.execute(
            sa.text("SELECT COUNT(*) FROM simulants WHERE connect_key = :key"),
            {"key": formatted_key},
        ).scalar()

        if result == 0:
            return formatted_key

    raise ValueError(f"Failed to generate unique connect key after {max_attempts} attempts")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_simulants_connect_key"), table_name = "simulants")
    op.drop_column("simulants", "connect_key")
    # ### end Alembic commands ###
