"""use_about_me_in_chats

Revision ID: 57f8712f47c2
Revises: 2791b8eece2e
Create Date: 2025-12-19 18:17:23.603069

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57f8712f47c2"
down_revision: Union[str, None] = "2791b8eece2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_configs",
        sa.Column(
            "use_about_me",
            sa.Boolean(),
            server_default = sa.text("true"),
            nullable = False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_configs", "use_about_me")
    # ### end Alembic commands ###
