"""price_alert_owners

Revision ID: 5e420f984e8d
Revises: 541b08819f2d
Create Date: 2025-06-29 01:33:11.635390

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e420f984e8d"
down_revision: Union[str, None] = "541b08819f2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Delete all existing price alerts since they won't have owner_id
    # noinspection SqlWithoutWhere
    op.execute("DELETE FROM price_alerts")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("price_alerts", sa.Column("owner_id", sa.UUID(), nullable = False))
    op.create_foreign_key("price_alerts_owner_id_fkey", "price_alerts", "simulants", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("price_alerts_owner_id_fkey", "price_alerts", type_ = "foreignkey")
    op.drop_column("price_alerts", "owner_id")
    # ### end Alembic commands ###
