"""payers_in_usage_records

Revision ID: 683fb395b513
Revises: c9ee31e7fae9
Create Date: 2026-02-17 19:13:26.433051

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "683fb395b513"
down_revision: Union[str, None] = "c9ee31e7fae9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        UPDATE usage_records
        SET payer_id = COALESCE(
            (SELECT sponsor_id FROM sponsorships WHERE receiver_id = usage_records.user_id LIMIT 1),
            user_id
        )
        WHERE payer_id IS NULL
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "usage_records",
        "payer_id",
        existing_type = sa.UUID(),
        nullable = False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "usage_records",
        "payer_id",
        existing_type = sa.UUID(),
        nullable = True,
    )
    # ### end Alembic commands ###
