"""attachments_external_id_rename

Revision ID: 907f4ee4b4cf
Revises: 4711ede6d1b3
Create Date: 2025-08-10 14:22:29.910742

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "907f4ee4b4cf"
down_revision: Union[str, None] = "4711ede6d1b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_message_attachments", sa.Column("external_id", sa.String(), nullable = True))
    op.execute(sa.text("UPDATE chat_message_attachments SET external_id = ext_id"))
    op.drop_index(op.f("idx_ext_id"), table_name = "chat_message_attachments")
    op.create_index("idx_external_id", "chat_message_attachments", ["external_id"], unique = False)
    op.drop_column("chat_message_attachments", "ext_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_message_attachments", sa.Column("ext_id", sa.VARCHAR(), autoincrement = False, nullable = True))
    op.execute(sa.text("UPDATE chat_message_attachments SET ext_id = external_id"))
    op.drop_index("idx_external_id", table_name = "chat_message_attachments")
    op.create_index(op.f("idx_ext_id"), "chat_message_attachments", ["ext_id"], unique = False)
    op.drop_column("chat_message_attachments", "external_id")
    # ### end Alembic commands ###
