"""Direct user reference

Revision ID: 94fb5ae49abb
Revises: 01b6bbaa0e0f
Create Date: 2024-06-08 13:35:27.294909

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94fb5ae49abb'
down_revision: Union[str, None] = '01b6bbaa0e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('author_id', sa.UUID(), nullable = True))
    op.create_foreign_key(None, 'chat_messages', 'simulants', ['author_id'], ['id'])
    op.drop_column('chat_messages', 'author_username')
    op.drop_column('chat_messages', 'author_name')
    op.add_column('simulants', sa.Column('telegram_user_id', sa.Integer(), nullable = True))
    op.create_index(op.f('ix_simulants_telegram_user_id'), 'simulants', ['telegram_user_id'], unique = True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulants_telegram_user_id'), table_name = 'simulants')
    op.drop_column('simulants', 'telegram_user_id')
    op.add_column('chat_messages', sa.Column('author_name', sa.VARCHAR(), autoincrement = False, nullable = True))
    op.add_column('chat_messages', sa.Column('author_username', sa.VARCHAR(), autoincrement = False, nullable = True))
    # noinspection PyTypeChecker
    op.drop_constraint(None, 'chat_messages', type_ = 'foreignkey')
    op.drop_column('chat_messages', 'author_id')
    # ### end Alembic commands ###
