"""release_notifications

Revision ID: 9d2363ca98db
Revises: 31bcb8d29bc1
Create Date: 2025-05-09 20:16:00.844425

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d2363ca98db"
down_revision: Union[str, None] = "31bcb8d29bc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Let's create the enum type first
    release_notifications_enum = sa.Enum("none", "major", "minor", "all", name = "releasenotifications")
    release_notifications_enum.create(op.get_bind())

    # Let's add column with server_default to set value for existing rows
    op.add_column(
        "chat_configs",
        sa.Column(
            "release_notifications",
            release_notifications_enum,
            server_default = "all",
            nullable = False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_configs", "release_notifications")
    # Drop the enum type
    sa.Enum(name = "releasenotifications").drop(op.get_bind())
    # ### end Alembic commands ###
