"""failed_tool_calls_flag

Revision ID: a4a7043df8b2
Revises: 683fb395b513
Create Date: 2026-02-19 17:42:11.226203

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4a7043df8b2"
down_revision: Union[str, None] = "683fb395b513"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage_records", sa.Column("is_failed", sa.Boolean(), server_default = "false", nullable = False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_records", "is_failed")
    # ### end Alembic commands ###
