"""purchase_history

Revision ID: a65f7245c5cb
Revises: ad464f773a20
Create Date: 2026-02-07 17:41:49.133987

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a65f7245c5cb"
down_revision: Union[str, None] = "ad464f773a20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_records",
        sa.Column("id", sa.UUID(), nullable = False),
        sa.Column("user_id", sa.UUID(), nullable = True),
        sa.Column("seller_id", sa.String(), nullable = False),
        sa.Column("sale_id", sa.String(), nullable = False),
        sa.Column("sale_timestamp", sa.DateTime(), nullable = False),
        sa.Column("price", sa.Integer(), nullable = False),
        sa.Column("product_id", sa.String(), nullable = False),
        sa.Column("product_name", sa.String(), nullable = False),
        sa.Column("product_permalink", sa.String(), nullable = False),
        sa.Column("short_product_id", sa.String(), nullable = False),
        sa.Column("license_key", sa.String(), nullable = True),
        sa.Column("quantity", sa.Integer(), nullable = False),
        sa.Column("gumroad_fee", sa.Integer(), nullable = False),
        sa.Column("affiliate_credit_amount_cents", sa.Integer(), nullable = False),
        sa.Column("discover_fee_charge", sa.Boolean(), nullable = False),
        sa.Column("url_params", sa.JSON(), nullable = True),
        sa.Column("custom_fields", sa.JSON(), nullable = True),
        sa.Column("test", sa.Boolean(), nullable = False),
        sa.Column("is_preorder_authorization", sa.Boolean(), nullable = False),
        sa.Column("refunded", sa.Boolean(), nullable = False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["simulants.id"], name = "purchase_records_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sale_id"),
    )
    op.create_index(
        "idx_purchase_records_license_key",
        "purchase_records",
        ["license_key"],
        unique = False,
    )
    op.create_index(
        "idx_purchase_records_user_timestamp",
        "purchase_records",
        ["user_id", sa.literal_column("sale_timestamp DESC")],
        unique = False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_purchase_records_user_timestamp", table_name = "purchase_records")
    op.drop_index("idx_purchase_records_license_key", table_name = "purchase_records")
    op.drop_table("purchase_records")
    # ### end Alembic commands ###
