"""Telegram uniqueness fix

Revision ID: a7aae15ea264
Revises: 94fb5ae49abb
Create Date: 2024-06-08 20:24:41.850263

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7aae15ea264"
down_revision: Union[str, None] = "94fb5ae49abb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_simulants_telegram_chat_id", table_name = "simulants")
    op.drop_index("ix_simulants_telegram_username", table_name = "simulants")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_simulants_telegram_username", "simulants", ["telegram_username"], unique = True)
    op.create_index("ix_simulants_telegram_chat_id", "simulants", ["telegram_chat_id"], unique = True)
    # ### end Alembic commands ###
