"""usage_records

Revision ID: ad464f773a20
Revises: 338582422265
Create Date: 2026-01-30 18:28:21.774045

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad464f773a20"
down_revision: Union[str, None] = "338582422265"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usage_records",
        sa.Column("id", sa.UUID(), nullable = False),
        sa.Column("user_id", sa.UUID(), nullable = False),
        sa.Column("chat_id", sa.UUID(), nullable = True),
        sa.Column("tool_id", sa.String(), nullable = False),
        sa.Column("tool_name", sa.String(), nullable = False),
        sa.Column("provider_id", sa.String(), nullable = False),
        sa.Column("provider_name", sa.String(), nullable = False),
        sa.Column("purpose", sa.String(), nullable = False),
        sa.Column("timestamp", sa.DateTime(), nullable = False),
        sa.Column("runtime_seconds", sa.Float(), nullable = False),
        sa.Column("remote_runtime_seconds", sa.Float(), nullable = True),
        sa.Column("model_cost_credits", sa.Float(), nullable = False),
        sa.Column("remote_runtime_cost_credits", sa.Float(), nullable = False),
        sa.Column("api_call_cost_credits", sa.Float(), nullable = False),
        sa.Column("maintenance_fee_credits", sa.Float(), nullable = False),
        sa.Column("total_cost_credits", sa.Float(), nullable = False),
        sa.Column("input_tokens", sa.Integer(), nullable = True),
        sa.Column("output_tokens", sa.Integer(), nullable = True),
        sa.Column("search_tokens", sa.Integer(), nullable = True),
        sa.Column("total_tokens", sa.Integer(), nullable = True),
        sa.Column("output_image_sizes", sa.JSON(), nullable = True),
        sa.Column("input_image_sizes", sa.JSON(), nullable = True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_usage_records_user_timestamp",
        "usage_records",
        ["user_id", sa.literal_column("timestamp DESC")],
        unique = False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_usage_records_user_timestamp", table_name = "usage_records")
    op.drop_table("usage_records")
    # ### end Alembic commands ###
