"""chat_media_modes

Revision ID: bd6531868af1
Revises: 5472fe3215da
Create Date: 2025-12-16 19:11:01.947571

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "bd6531868af1"
down_revision: Union[str, None] = "5472fe3215da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists, if so drop it first (in case of partial migration)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("chat_configs")]
    if "media_mode" in columns:
        op.drop_column("chat_configs", "media_mode")

    # Drop enum type if it exists (in case of partial migration)
    op.execute(text("DROP TYPE IF EXISTS mediamode CASCADE"))

    # Let's create the enum type first
    media_mode_enum = sa.Enum("photo", "file", "all", name = "mediamode")
    media_mode_enum.create(op.get_bind())

    # Let's add column with server_default to set value for existing rows
    op.add_column(
        "chat_configs",
        sa.Column(
            "media_mode",
            media_mode_enum,
            server_default = "photo",
            nullable = False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_configs", "media_mode")
    # Drop the enum type
    sa.Enum(name = "mediamode").drop(op.get_bind())
    # ### end Alembic commands ###
