"""Additional chat properties

Revision ID: c4b16e92a201
Revises: 3ba10b2b7ae5
Create Date: 2024-06-10 22:26:49.419326

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4b16e92a201"
down_revision: Union[str, None] = "3ba10b2b7ae5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_configs", sa.Column("title", sa.String(), nullable = True))
    op.add_column("chat_configs", sa.Column("is_private", sa.Boolean(), nullable = False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_configs", "is_private")
    op.drop_column("chat_configs", "title")
    # ### end Alembic commands ###
