"""spending_credits

Revision ID: c9ee31e7fae9
Revises: a65f7245c5cb
Create Date: 2026-02-15 19:22:58.141287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9ee31e7fae9"
down_revision: Union[str, None] = "a65f7245c5cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulants",
        sa.Column("credit_balance", sa.Float(), server_default = sa.text("0"), nullable = False),
    )
    op.add_column(
        "usage_records",
        sa.Column("payer_id", sa.UUID(), nullable = True),
    )
    op.add_column(
        "usage_records",
        sa.Column("uses_credits", sa.Boolean(), server_default = sa.text("false"), nullable = False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_records", "uses_credits")
    op.drop_column("usage_records", "payer_id")
    op.drop_column("simulants", "credit_balance")
    # ### end Alembic commands ###
