"""Rename history to messages

Revision ID: cb35264b5443
Revises: cdaba00854b2
Create Date: 2024-05-20 17:44:30.737046

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cb35264b5443"
down_revision: Union[str, None] = "cdaba00854b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_chat_message", "chat_history", type_ = "primary")
    op.drop_constraint("uq_message_per_chat", "chat_history", type_ = "unique")
    op.drop_table("chat_history")
    op.create_table(
        "chat_messages",
        sa.Column("chat_id", sa.String(), nullable = False),
        sa.Column("message_id", sa.String(), nullable = False),
        sa.Column("author_name", sa.String(), nullable = True),
        sa.Column("author_username", sa.String(), nullable = True),
        sa.Column("sent_at", sa.DateTime(), nullable = False),
        sa.Column("text", sa.Text(), nullable = False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat_configs.chat_id"], ),
        sa.PrimaryKeyConstraint("chat_id", "message_id", name = "pk_chat_message"),
        sa.UniqueConstraint("chat_id", "message_id", name = "uq_message_per_chat"),
    )
    op.create_unique_constraint("uq_message_per_chat", "chat_messages", ["chat_id", "message_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_chat_message", "chat_messages", type_ = "primary")
    op.drop_constraint("uq_message_per_chat", "chat_messages", type_ = "unique")
    op.drop_table("chat_messages")
    op.create_table(
        "chat_history",
        sa.Column("chat_id", sa.VARCHAR(), autoincrement = False, nullable = False),
        sa.Column("message_id", sa.VARCHAR(), autoincrement = False, nullable = False),
        sa.Column("author_name", sa.VARCHAR(), autoincrement = False, nullable = True),
        sa.Column("author_username", sa.VARCHAR(), autoincrement = False, nullable = True),
        sa.Column("sent_at", postgresql.TIMESTAMP(), autoincrement = False, nullable = False),
        sa.Column("text", sa.TEXT(), autoincrement = False, nullable = False),
        sa.ForeignKeyConstraint(["chat_id"], ["chat_configs.chat_id"], name = "chat_history_chat_id_fkey"),
        sa.PrimaryKeyConstraint("chat_id", "message_id", name = "pk_chat_message"),
        sa.UniqueConstraint("chat_id", "message_id", name = "uq_message_per_chat"),
    )
    # ### end Alembic commands ###
