"""Removed invite ID

Revision ID: cdaba00854b2
Revises: 9f03626e370e
Create Date: 2024-05-20 13:32:15.685087

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cdaba00854b2'
down_revision: Union[str, None] = '9f03626e370e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invites', 'id')
    op.create_primary_key('pk_invites', 'invites', ['sender_id', 'receiver_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk_invites', 'invites', type_ = 'primary')
    op.add_column('invites', sa.Column('id', sa.UUID(), autoincrement = False, nullable = False))
    # ### end Alembic commands ###
