"""x_twitter_api_keys

Revision ID: d6f7c1204b44
Revises: e36296a560ef
Create Date: 2026-03-14 19:18:01.044967

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import BYTEA

# revision identifiers, used by Alembic.
revision: str = "d6f7c1204b44"
down_revision: Union[str, None] = "e36296a560ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulants", sa.Column("x_key", BYTEA, nullable = True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulants", "x_key")
    # ### end Alembic commands ###
