"""onboarding_and_waitlists

Revision ID: e36296a560ef
Revises: a4a7043df8b2
Create Date: 2026-03-05 12:59:48.263350

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e36296a560ef"
down_revision: Union[str, None] = "a4a7043df8b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simulants", sa.Column("is_on_waitlist", sa.Boolean(), server_default = sa.text("false"), nullable = False))  # noqa: E501
    op.add_column("simulants", sa.Column("is_invited_to_start", sa.Boolean(), server_default = sa.text("false"), nullable = False))  # noqa: E501
    op.add_column("simulants", sa.Column("are_policies_accepted", sa.Boolean(), server_default = sa.text("false"), nullable = False))  # noqa: E501
    op.execute(
        sa.text(
            """
            UPDATE simulants
            SET
                is_on_waitlist = false,
                is_invited_to_start = false,
                are_policies_accepted = true
            """,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulants", "are_policies_accepted")
    op.drop_column("simulants", "is_invited_to_start")
    op.drop_column("simulants", "is_on_waitlist")
    # ### end Alembic commands ###
