"""credit_transfers

Revision ID: f81c0b60d07e
Revises: 4a9e7ab95bf7
Create Date: 2026-04-04 16:30:26.656134

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f81c0b60d07e"
down_revision: Union[str, None] = "4a9e7ab95bf7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # leftover: encrypted_messages migration created the BYTEA column as nullable; enforce NOT NULL to match the model
    op.alter_column("chat_messages", "text", existing_type = postgresql.BYTEA(), nullable = False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usage_records", sa.Column("counterpart_id", sa.UUID(), nullable = True))
    op.add_column("usage_records", sa.Column("note", sa.String(), nullable = True))
    op.add_column("usage_records", sa.Column("participant_details", sa.JSON(), nullable = True))
    op.create_index(
        "idx_usage_records_counterpart_timestamp", "usage_records",
        ["counterpart_id", sa.literal_column("timestamp DESC")], unique = False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # leftover: encrypted_messages migration created the BYTEA column as nullable
    op.drop_index("idx_usage_records_counterpart_timestamp", table_name = "usage_records")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usage_records", "participant_details")
    op.drop_column("usage_records", "note")
    op.drop_column("usage_records", "counterpart_id")
    op.alter_column("chat_messages", "text", existing_type = postgresql.BYTEA(), nullable = True)
    # ### end Alembic commands ###
